### PR TITLE
some cleanups / small fixes

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
hey :)

thanks for writing that tool!

I just dumped pidgin/libpurple (for security reasons) and moved to gajim and it was convenient not having to re-authenticate with everybody.

While reading the src and using the tool, I found some minor issues and cleaned up a bit.
Please rather look at the individual changesets than at the overall changes - due to the indentation fix it looks like more change than it really is.

I did my own key/fp conversion using the final version, so it is practically tested.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
ping

**Comment by ThomasWaldmann** [comment]
ping.

**Comment by micahflee** [comment]
Hey, sorry I ignored this for oh, so many months. These look good, merging.

**Comment by ThomasWaldmann** [comment]
thanks :)

**Pull request merged**
